# Generated by Django 4.1.7 on 2023-03-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Localizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedWaybills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Waybills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_road_time', models.PositiveIntegerField(null=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='service_function.localization')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='service_function.localization')),
            ],
            options={
                'verbose_name_plural': 'Waybils',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.UUIDField(unique=True)),
                ('road_time', models.PositiveIntegerField()),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_function.waybills')),
            ],
            options={
                'verbose_name_plural': 'Transports',
            },
        ),
    ]
