# Generated by Django 4.1.7 on 2023-03-06 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.UUIDField(default=uuid.UUID('7d28309f-6659-4fbf-be75-051f4f1c2f40'), unique=True)),
                ('road_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waybills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_road_time', models.PositiveIntegerField()),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='service_function.localization')),
                ('list_of_transport', models.ManyToManyField(to='service_function.transport')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='service_function.localization')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_function.waybills'),
        ),
    ]
