# Generated by Django 4.1.7 on 2023-03-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Localizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedWaybills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.UUIDField(unique=True)),
                ('road_time', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Transports',
            },
        ),
        migrations.CreateModel(
            name='Waybills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_road_time', models.PositiveIntegerField(null=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='service_function.localization')),
                ('list_of_transport', models.ManyToManyField(related_name='transports', to='service_function.transport')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='service_function.localization')),
            ],
            options={
                'verbose_name_plural': 'Waybils',
                'ordering': ['max_road_time'],
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='waybill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_function.waybills'),
        ),
    ]
