# Generated by Django 4.1.7 on 2023-03-06 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='code_name',
            field=models.UUIDField(default=uuid.UUID('ae6d476e-f06a-4d5f-8b66-f3b0821617b2'), unique=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='waybill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='service_function.waybills'),
        ),
    ]
