# Generated by Django 4.1.7 on 2023-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybills',
            name='towns',
            field=models.ManyToManyField(blank=True, null=True, to='service_function.localization'),
        ),
    ]
