# Generated by Django 4.1.7 on 2023-03-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybills',
            name='list_of_transport',
        ),
    ]
