# Generated by Django 4.1.7 on 2023-03-06 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0002_alter_transport_code_name_alter_transport_waybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='code_name',
            field=models.UUIDField(default=uuid.UUID('97991f00-aeb9-4ae4-a289-d7647accc340'), unique=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='waybill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_function.waybills'),
        ),
    ]
