# Generated by Django 4.1.7 on 2023-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0002_waybills_towns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybills',
            name='towns',
            field=models.ManyToManyField(blank=True, to='service_function.localization'),
        ),
    ]
