# Generated by Django 4.1.7 on 2023-03-07 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0003_alter_transport_code_name_alter_transport_waybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='code_name',
            field=models.UUIDField(default=uuid.UUID('0979cab8-d8de-46f3-b4b1-406cb12c6e6e'), unique=True),
        ),
        migrations.AlterField(
            model_name='waybills',
            name='max_road_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
