# Generated by Django 4.1.7 on 2023-03-07 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0005_alter_transport_code_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='code_name',
            field=models.UUIDField(default=uuid.UUID('eb7d9042-c693-4d37-ac1f-ee82db8befd8'), unique=True),
        ),
    ]
