# Generated by Django 4.1.7 on 2023-03-07 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0006_alter_transport_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='code_name',
            field=models.UUIDField(default=uuid.UUID('bff3f930-0155-4a22-a06c-2faf4c0a2fd8'), unique=True),
        ),
    ]
