# Generated by Django 4.1.7 on 2023-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_function', '0007_alter_transport_code_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localization',
            options={'verbose_name_plural': 'Localizations'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name_plural': 'Transports'},
        ),
        migrations.AlterModelOptions(
            name='waybills',
            options={'verbose_name_plural': 'Waybils'},
        ),
        migrations.AlterField(
            model_name='transport',
            name='code_name',
            field=models.UUIDField(unique=True),
        ),
    ]
